name: Main Release

on:
  push:
    branches:
      - [main, enhance/continuous-integration]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm i

      - name: Build and Bundle
        run: npm run build && npm run bundle

      - name: ls
        run: ls
      
      # - name: package and upload
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     release_name: fluid.waveform~
      #     body: "This is a nightly build of the FluCoMa Max package. As such, be warned there may be bugs or other unexpected behaviour. The build hash is ${{ github.sha }}"
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: FluCoMa-Max-nightly.zip
      #     asset_name: FluCoMa-Max-nightly.zip
      #     tag: ${{ github.ref }}
      #     overwrite: true
        
