name: Release latest build

on:
  push:
    branches: [main, enhance/continuous-integration]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm i

      - name: Build and Bundle
        run: npm run build && npm run bundle

      - name: Create tar.gz
        run: tar -zcvf fluid.waveform.tar.gz max-package/
      
      - name: package and upload
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: fluid.waveform~
          body: "This is the latest release of the fluid.waveform~ js code. It is intended to be used in the FluCoMa Max Package."
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fluid.waveform.tar.gz
          asset_name: fluid.waveform.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
        
