name: Release latest build

on:
  workflow_dispatch:
  push:
    branches: [main, ci/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Build and Bundle
        run: npm run build && npm run bundle

      - name: Create tar.gz
        run: tar -zcvf fluid.waveform.tar.gz max-package/

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: Fluid Waveform Build
          body: "This is a release build of the FluCoMa Max package. The build hash is ${{ github.sha }}"
          files: fluid.waveform.tar.gz
          prerelease: false
          tag_name: build
          draft: false
